# This file configures the analyzer to use the lint rule set from `package:flutter_lints`

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Additional rules
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    unnecessary_this: true
    avoid_print: true
    avoid_unnecessary_containers: true
    prefer_single_quotes: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
